# Practice on Git Hub Actions 
# Part 1. Basics
#
# by Anatolii M.

name: GitHub-Actions-Basics

# Global env variable for all jobs and steps
env:
  APPLICATION_NAME: "vteApp"
  IMAGE_NAME: "nodejs-ver-${{ github.run_id }}"

on: 
  push: 
    branches: ["main"]

jobs:
  test:
    name: Run testings jobs 
    runs-on: ubuntu-latest
   
    steps:
      - name: Print Messages for first step for testings
        run: echo "Run Testing job"
      - name: Run multi-run script
        run: |
          echo The project must contain steps:
          echo test, build and deploy.

      - name: View global env variable
        run: echo "Application name - ${{ env.APPLICATION_NAME }}"
          
      - name: View in current folder
        run: | 
          ls -la
          df -h

      - name: Git clone repo
        uses: actions/checkout@v4

      - name: List files in folders
        run : ls -la
    
  deploy:
    name: Run deploy jobs
    runs-on: ubuntu-24.04
    needs: test
    if: success()
    env:
      VAR_JOB1: "Variable1 for job level"
      VAR_JOB2: "Variable2 for job level"

    steps:
      - name: View version OS
        run: lsb_release -a
      - name: Print Message
        run: echo "Hello from Deploy job"
      - name: Print image name for deploy
        run: echo "Image name is ${{ env.IMAGE_NAME }}"
      - name: Check some a package on the runner
        run: aws --version 
      - name: Check present a docker
        run: docker --version
      - name: Print jobs variable
        run: |
          echo "Variable1 - ${{ env.VAR_JOB1 }}"
          echo "Variable2 - ${{ env.VAR_JOB2 }}"
          echo "Variable3 - $STEP_VAR"
        env:
          STEP_VAR: "This is local environment variable"
