# Practice on Git Hub Actions 
# Part 1. Basics
#
# by Anatolii M.

name: GitHub-Actions-Basics

# Global env variable for all jobs and steps
env:
  APPLICATION_NAME: "vteApp"
  IMAGE_NAME: "nodejs-ver-${{ github.run_id }}"

on: 
  push: 
    branches: ["main"]

jobs:
  test:
    name: Run testings jobs 
    runs-on: ubuntu-latest
   
    steps:
      - name: Print Messages for first step for testings
        run: echo "Run Testing job"
      - name: Run multi-run script
        run: |
          echo The project must contain steps:
          echo test, build and deploy.

      - name: View global env variable
        run: echo "Application name - ${{ env.APPLICATION_NAME }}"
    
  deploy:
    name: Run deploy jobs
    runs-on: ubuntu-24.04
    needs: test
    if: success()

    steps:
      - name: View version OS
        run: lsb_release -a
      - name: Print Message
        run: echo "Hello from Deploy job"
      - name: Print image name for deploy
        run: echo "Image name is ${{ env.IMAGE_NAME }}"
